services:
  open-webui:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'WEBUI_SECRET_KEY='
      # Add any additional environment variables needed for your OpenAI or other model integrations
      - 'OPENAI_API_KEY=${OPENAI_API_KEY-}'
      - 'OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL-}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    expose:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: nginx-webui
    ports:
      - ${OPEN_WEBUI_PORT-3000}:80
    depends_on:
      - open-webui
    restart: unless-stopped

volumes:
  open-webui: {}