services:
  ollama:
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-amdgpu}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
