services:
  open-webui:
    container_name: app
    ports:
      - "3000:8080"
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG}
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OLLAMA_BASE_URL=http://127.0.0.1:11434 
      - ENABLE_EVALUATION_ARENA_MODELS=false
      - ENABLE_SIGNUP=true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - webui-network
    expose:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: webui-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - open-webui
    networks:
      - webui-network
    volumes:
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot

volumes:
  open-webui: {}

networks:
  webui-network:
    driver: bridge
