version: '3.8'
services:

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  open-webui:
    env_file:
      - .env
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      # Mount the favicons volume to the location where your application expects the assets.
      - favicons:/app/static/favicon:ro
    depends_on:
      - searxng
    ports:
      - "${OPEN_WEBUI_PORT-3000}:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  tika:
    image: apache/tika:3.1.0.0-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  favicons: {}
