services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    restart: always

volumes:
  open-webui-data:
