apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gpt-portal-ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: gpt-portal
spec:
  serviceName: "gpt-portal-ollama"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: gpt-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: gpt-portal
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        volumeMounts:
        - name: gpt-portal-ollama-volume
          mountPath: /root/.ollama
        tty: true
      tolerations:
      - key: "karpenter.sh/capacity-type"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
  volumeClaimTemplates:
  - metadata:
      name: gpt-portal-ollama-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: aws-ebs-sc
      resources:
        requests:
          storage: 30Gi