name: Bug Report
description: Create a detailed bug report to help us improve RAUX.
title: '[Bug]: '
labels: ['bug', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report

        **Before submitting**: Please check the [Issues](https://github.com/aigdat/raux/issues) or [Discussions](https://github.com/aigdat/raux/discussions) to see if a similar issue has already been reported.
        If unsure, start a discussion first.

        Thank you for contributing to RAUX!

  - type: checkboxes
    id: issue-check
    attributes:
      label: Preliminary Checks
      description: Confirm you've done these steps before submitting.
      options:
        - label: I have searched the existing issues and discussions.
          required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install RAUX?
      options:
        - Standalone Installer
        - Coupled with GAIA
        - Git Clone
    validations:
      required: true

  - type: input
    id: raux-version
    attributes:
      label: RAUX Version
      description: Specify the version (e.g., v0.3.11)
    validations:
      required: true

  - type: input
    id: ollama-version
    attributes:
      label: Ollama Version (if applicable)
      description: Specify the version (e.g., v0.2.0, or v0.1.32-rc1)
    validations:
      required: false

  - type: input
    id: lemonade-version
    attributes:
      label: Lemonade Version (if applicable)
      description: Specify the version (e.g., v0.2.0, or v0.1.32-rc1)
    validations:
      required: false

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Specify the OS (e.g., Windows 10, macOS Sonoma, Ubuntu 22.04)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Specify the browser/version (e.g., Chrome 100.0, Firefox 98.0)
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Ensure the following prerequisites have been met.
      options:
        - label: I have read and followed all instructions in `README.md`.
          required: true
        - label: I have listed steps to reproduce the bug in detail.
          required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what should have happened.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Providing clear, step-by-step instructions helps us reproduce and fix the issue faster. If we can't reproduce it, we can't fix it.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error message '...'
    validations:
      required: true

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Logs & Screenshots
      description: Include relevant logs, errors, or screenshots to help diagnose the issue.
      placeholder: 'Attach logs from the browser console, or error messages.'
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Provide any extra details that may assist in understanding the issue.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Note
        If the bug report is incomplete or does not follow instructions (especially reproduction steps), it may be closed without review.
        Ensure that you've followed all the [README.md](https://github.com/aigdat/raux/blob/main/README.md) guidelines.
        Thank you for contributing to RAUX!
