name: Feature Request
description: Suggest an idea for this project
title: 'feat: '
labels: ['triage', 'enhancement']
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request

        **Before submitting**: Please check the [Issues](https://github.com/aigdat/raux/issues) or [Discussions](https://github.com/aigdat/raux/discussions) to see if a similar request has been posted.
        If you're unsure, start a discussion first.

        Thank you for contributing to RAUX!

        ### Collaborate respectfully
        We value a **constructive attitude**, so please be mindful of your communication. If negativity is part of your approach, our capacity to engage may be limited. We're here to help if you're **open to learning** and **communicating positively**.

        Remember:


        ### Contributing
        If you encounter an issue, we highly encourage you to submit a pull request or fork the project. We actively work to prevent contributor burnout to maintain the quality and continuity of RAUX.


  - type: checkboxes
    id: existing-issue
    attributes:
      label: Check Existing Issues
      description: Please confirm that you've checked for existing similar requests
      options:
        - label: I have searched the existing issues and discussions.
          required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please provide a clear and concise description of what the problem is.
      placeholder: "Ex. I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Desired Solution you'd like
      description: Clearly describe what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
