name: Deploy Open WebUI via Tailscale

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via Docker Compose v2 (Tailscale IP)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.TAILSCALE_SERVER_IP }} "
            cd /home/mergefeat/hkust-open-webui

            export OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}'
            export OPENAI_API_BASE_URL='${{ secrets.OPENAI_API_BASE_URL }}'
            export OPEN_WEBUI_PORT='${{ secrets.OPEN_WEBUI_PORT }}'

            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
          "
